name: Certora

on:
  push:
    branches:
      - master
      - Certora/ComposableStablePool

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.6, cache: 'pip' }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install certora
        run: pip install certora-cli

      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.4/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.4
      - name: Verify rule ${{ matrix.script }}
        run: |
          touch certora/applyHarness.patch
          make -C certora munged
          echo "key length" ${#CERTORAKEY}
          sh certora/scripts/${{ matrix.script }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

    strategy:
      fail-fast: false
      max-parallel: 4

      matrix:
        script:
         - verifyPauseRecovery.sh
         - verifyComposableStablePool.sh
         - verifyWordCodec.sh
      
